### ISSUE TITLE
API Client is not able to unset IPAM IP-Address Role

### ISSUE THREAD

**Issue by twink0r** [fbreckle/go-netbox#15]
Hi!

I'm trying to unset the role of WritableIPAddress, but it seems not to work. 

**Snippet (part of a Terraform provider)**
```
if d.HasChange("role") {
  if role := d.Get("role"); role.(string) == "" {
	  data.Role = " "
  } else {
	  data.Role = role.(string)
  }
}
```

This snippet above ends in `map[role:[  is not a valid choice.]]` but it should be null because the field is omitempty tagged.

**Comment by fbreckle** [comment]
Should it be null? The [encoding/json docs](https://pkg.go.dev/encoding/json#Marshal) says that 

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string. 

So I assume that `" "` does not qualify as "empty string" (but `""` would).

**Comment by twink0r** [comment]
I tried both variants, either `" "` and `" "` do not work. If I set this to `""` it does not change it via API
