### ISSUE TITLE
Add support for multiple Tags 

### ISSUE THREAD

**Issue by twink0r** [fbreckle/go-netbox#22]
Hi,

I want to implement the tags filter in e-breuninger/netbox. But right now it supports only one tag per request. But most Netbox objects needs to filtered by multiple tags such as environment and service.

For example (taken from netbox/client/virtualization/virtualization_virtual_machines_list_parameters.go)

```
if err := r.SetQueryParam("tag", qTag); err != nil {
  return err
}
```

**Comment by fbreckle** [comment]
Closed by #23
